# Standalone file: do not edit by hand
# Generated by: pkgtools from @unit tags
# ----------------------------------------------------------------------
library(pkgtools)

# unit test start: .singleton ----

test_that(".singleton unit test", {

  # Automatically generated test case from roxygen @unit tag
  # Do not edit here - follow the link to the source file.
  
  fixed_rnorm <- .singleton(rnorm(10))
  a <- fixed_rnorm()
  b <- fixed_rnorm()
  testthat::expect_equal(a, b)

  # generates a failure if the overall test is failing with a link to the 
  # source of the unit test:
  testthat::expect(rlang::caller_env(n = 2)$ok,
    failure_message = "Source link for failing @unit test.",
    srcref = srcref(srcfile("../../R/import-standalone-singleton.R"), c(30, 1, 30+1, 1))
  )
})

# unit test end: .singleton ----
# end of unit tests ----
