# Standalone file: do not edit by hand
# Generated by: pkgtools from @unit tags
# ----------------------------------------------------------------------
library(pkgtools)

# unit test start: roxy_tag_rd.roxy_tag_unit ----

test_that("roxy_tag_rd.roxy_tag_unit unit test", {

  # Automatically generated test case from roxygen @unit tag
  # Do not edit here - follow the link to the source file.
  
  testthat::expect_no_error(withCallingHandlers(
    {
      # for testing
      warning("should be suppressed")
    },
    warning = function(e) {
      message("Warning issued: ", e$message)
      invokeRestart("muffleWarning")
    }
  ))

  # generates a failure if the overall test is failing with a link to the 
  # source of the unit test:
  testthat::expect(rlang::caller_env(n = 2)$ok,
    failure_message = "Source link for failing @unit test.",
    srcref = srcref(srcfile("../../R/roxygen_unit.R"), c(58, 1, 58+1, 1))
  )
})

# unit test end: roxy_tag_rd.roxy_tag_unit ----
# end of unit tests ----
