# Standalone file: do not edit by hand
# Generated by: pkgtools from @unit tags
# ----------------------------------------------------------------------
library(pkgtools)

# unit test start: roxy_tag_rd.roxy_tag_unit ----

test_that("roxy_tag_rd.roxy_tag_unit unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/roxygen_unit.R", line=58)
  # or navigate to topic with <F2>
  F2 = roxy_tag_rd.roxy_tag_unit
  
  testthat::expect_no_error(withCallingHandlers(
    {
      # for testing
      warning("should be suppressed")
    },
    warning = function(e) {
      message("Warning issued: ", e$message)
      invokeRestart("muffleWarning")
    }
  ))
})

# unit test end: roxy_tag_rd.roxy_tag_unit ----
# end of unit tests ----
