# Standalone file: do not edit by hand
# Generated by: pkgtools from @unit tags
# ----------------------------------------------------------------------
library(pkgtools)

# unit test start: .lax_as_function ----

test_that(".lax_as_function unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/import-standalone-stack-tools.R", line=26)
  # or navigate to topic with <F2>
  F2 = .lax_as_function
  
  
  
  f1 = .lax_as_function(tolower)
  f2 = .lax_as_function(~ tolower(.x))
  f3 = .lax_as_function("hello world")
  
  testthat::expect_equal(f1, tolower)
  testthat::expect_equal(f2("HELLO WORLD"), f1("HELLO WORLD"))
  testthat::expect_equal(f3, f1("HELLO WORLD"))
  
})

# unit test end: .lax_as_function ----
# unit test start: .get_fn_name ----

test_that(".get_fn_name unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/import-standalone-stack-tools.R", line=49)
  # or navigate to topic with <F2>
  F2 = .get_fn_name
  
  
  
  f = tolower
  
  testthat::expect_equal(
    .get_fn_name(f),
    .get_fn_name(tolower)
  )
  
  testthat::expect_equal(
    .get_fn_name(.get_fn_name),
    ".get_fn_name"
  )
  
  testthat::expect_equal(
    .get_fn_name(function(x) x),
    "<unknown>"
  )
  
})

# unit test end: .get_fn_name ----
# unit test start: .search_call_stack ----

test_that(".search_call_stack unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/import-standalone-stack-tools.R", line=94)
  # or navigate to topic with <F2>
  F2 = .search_call_stack
  
  
  
  h = function() {
   df = .search_call_stack(.class = "data.frame")
   return(nrow(df))
  }
  
  g = function() {h()}
  
  f = function(x) {g()}
  
  testthat::expect_equal( f(datasets::iris), nrow(datasets::iris))
  
})

# unit test end: .search_call_stack ----
# unit test start: .find_namespace ----

test_that(".find_namespace unit test", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/import-standalone-stack-tools.R", line=140)
  # or navigate to topic with <F2>
  F2 = .find_namespace
  
  
  
  env = .find_namespace(rlang::abort)
  testthat::expect_equal(unname(getNamespaceName(env)), "rlang")
  
  # TODO: this test fails when running in testthat environment but not otherwise
  # env = new.env(parent=emptyenv())
  # assign("f", function() {"test"}, envir = env)
  # env2 = .find_namespace(env$f)
  # testthat::expect_null(.find_namespace(env$f))
  
})

# unit test end: .find_namespace ----
# end of unit tests ----
