# Standalone file: do not edit by hand
# Generated by: pkgtools from @unit tags
# ----------------------------------------------------------------------
library(pkgtools)

# .lax_as_function start ----

test_that(".lax_as_function unit test", {
  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/import-standalone-stack-tools.R", line=26)
  # or navigate to topic with <F2>
  F2 = .lax_as_function

  f1 = .lax_as_function(tolower)
  f2 = .lax_as_function(~ tolower(.x))
  f3 = .lax_as_function("hello world")

  testthat::expect_equal(f1, tolower)
  testthat::expect_equal(f2("HELLO WORLD"), f1("HELLO WORLD"))
  testthat::expect_equal(f3, f1("HELLO WORLD"))
})

# .lax_as_function end ----
# .get_fn_name start ----

test_that(".get_fn_name unit test", {
  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/import-standalone-stack-tools.R", line=49)
  # or navigate to topic with <F2>
  F2 = .get_fn_name

  f = tolower

  testthat::expect_equal(
    .get_fn_name(f),
    .get_fn_name(tolower)
  )

  testthat::expect_equal(
    .get_fn_name(.get_fn_name),
    ".get_fn_name"
  )

  testthat::expect_equal(
    .get_fn_name(function(x) x),
    "<unknown>"
  )
})

# .get_fn_name end ----
# .search_call_stack start ----

test_that(".search_call_stack unit test", {
  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/import-standalone-stack-tools.R", line=94)
  # or navigate to topic with <F2>
  F2 = .search_call_stack

  h = function() {
    df = .search_call_stack(.class = "data.frame")
    return(nrow(df))
  }

  g = function() {
    h()
  }

  f = function(x) {
    g()
  }

  testthat::expect_equal(f(iris), nrow(iris))
})

# .search_call_stack end ----
# .find_namespace start ----

test_that(".find_namespace unit test", {
  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/import-standalone-stack-tools.R", line=140)
  # or navigate to topic with <F2>
  F2 = .find_namespace

  env = .find_namespace(rlang::abort)
  testthat::expect_equal(unname(getNamespaceName(env)), "rlang")

  f = function() {
    "test"
  }
  testthat::expect_null(.find_namespace(f))
})

# .find_namespace end ----
# .glue_detect_output start ----

test_that(".glue_detect_output unit test", {
  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path="R/import-standalone-stack-tools.R", line=507)
  # or navigate to topic with <F2>
  F2 = .glue_detect_output

  content = c("sdlfksl", "  # X, Y and Z ----", "sdfskjfsdlk asdlkfjsdlkj")
  testthat::expect_equal(
    .glue_detect_output("# {name}, {value1} and {value2} ----", content),
    c(FALSE, TRUE, FALSE)
  )
})

# .glue_detect_output end ----
# insert before ----
