#' Parser for `@unit` tags
#'
#' The `@unit` tag can be used in `roxygen2` documentation
#' of a function to define unit testing code. This code will be written to a
#' testthat file.
#'
#' @inheritParams roxygen2::roxy_tag_parse
#' @concept document
#'
#' @importFrom roxygen2 roxy_tag_parse
#' @return a `roxy_tag` object with the `val` field set to the parsed value
#' @export
#' @examples
#' # This provides support to `roxygen2` and only gets executed in the context
#' # of `devtools::document()`. There is no interactive use of this function.
roxy_tag_parse.roxy_tag_unit = function(x) {
  roxygen2::tag_examples(x)
}

#' Support for `@unit` tags
#'
#' The `@unit` tag can be used in `roxygen2` documentation
#' of a function to define unit testing code. This code will be written to a
#' testthat file.
#'
#' @inheritParams roxygen2::roxy_tag_rd
#'
#' @importFrom roxygen2 roxy_tag_rd
#' @concept document
#' @return an `roxygen2::rd_section` (see `roxygen2` documentation)
#' @export
#'
#' @examples
#' # An example function definition:
#' fn_definition <- "
#' #' This is a title
#' #'
#' #' This is the description.
#' #'
#' #' @@md
#' #' @@unit
#' #' # unit testing code here:
#' #' testthat::expect_equal(f(), \"test\")
#' #' @@export
#' f <- function() {
#'   return(\"test\")
#' }
#' "
#'
#' # For this example we manually parse the function specification in `fn_definition`
#' # creating a .Rd block - normally this is done by `roxygen2` which then
#' # writes this to an .Rd file. This function is not intended to be used
#' # outside of a call to `devtools::document`.
#'
#' fn_definition = gsub("@@","@",fn_definition)
#' tmp = roxygen2::parse_text(fn_definition)
#' print(tmp[[1]])
#'
roxy_tag_rd.roxy_tag_unit = function(x, base_path, env) {
  raw_code = x$raw
  code = x$val
  block = .search_call_stack(.class = "roxy_block")
  fn = block$object$value
  topic = block$object$topic
  test_path = gsub("/R/", "/tests/testthat/test-unit-", block$file)
  fs::dir_create(fs::path_dir(test_path))
  pkg = unname(getNamespaceName(env))
  relpath = stringr::str_extract(block$file, "^(.*?/)(R/.*)$", 2)

  # Check to see if the test file exists. If not create and empty skeleton:
  if (!fs::file_exists(test_path)) {
    readr::write_lines(
      .create_skeleton(unit_test_skeleton, pkg = pkg),
      test_path
    )
  }

  start_glue = "# {name} start ----"
  end_glue = "# {name} end ----"

  test_lines = readr::read_lines(test_path)

  # Get rid of tests for functions that have been removed:
  # check for blocks that match the fence format
  test_block_lines = test_lines[.glue_detect_output(start_glue, test_lines)]
  # extract names of functions under test from the fence
  test_block_data = .glue_recover_pieces(start_glue, test_block_lines)
  # make sure function still exists in the namespace being documented
  test_block_data = test_block_data %>%
    dplyr::filter(!name %in% ls(env, all.names = TRUE))
  # delete unmatched tests
  for (name in test_block_data$name) {
    test_lines = .delete_fenced_block(test_lines, x)
  }

  # modify the existing block or add a new one at the end
  test_lines = .update_fenced_block(
    test_lines,
    .template = unit_test_call,
    name = topic,
    path = relpath,
    line = x$line,
    # double space indent. Code could be vector I guess.
    code = paste0("  ", gsub("\n", "\n  ", raw_code))
  )

  # write the new block out to the test file
  readr::write_lines(test_lines, test_path)

  # write the code into the Rd as a "Unit tests" section
  roxygen2::rd_section("unit", list(code = format(code)))
}

#' @export
format.rd_section_unit = function(x, ...) {
  whisker::whisker.render(unit_test_section, x$value)
}

# Unit testing whisker templates ----

unit_test_section = "
{{#code}}
\\section{Unit tests}{
\\code{
\\preformatted{
{{{.}}}
}
}
}
{{/code}}
"

unit_test_skeleton = "# Standalone file: do not edit by hand
# Generated by: pkgtools from @unit tags
# ----------------------------------------------------------------------
library({{{pkg}}})
"

unit_test_call = "
test_that(\"{{{name}}} unit test\", {

  # generated by roxygen @unit tag
  # edit this at:
  # rstudioapi::documentOpen(path=\"{{{path}}}\", line={{{line}}})
  # or navigate to topic with <F2>
  F2 = {{{name}}}
  
{{{code}}}
})
"
