#' Use a template file
#'
#' @param .template_name if not given a dialog will be presented with the
#'   options
#' @param ... supplied as parameters to the template. template placeholders such
#'   as \code{`xxx.#name#_yyy`}, will be substituted with \code{xxx.myname_yyy}
#'   if `name="myname"`. The first value of this list will be used for
#'   \code{`##`} placeholders
#' @param .overwrite overwrte the destination file if it exists
#' @param .destfile if given will write the expanded template here.
#' @concept usethis
#'
#' @returns the written file name
#' @export
use_template = function(
  .template_name = NULL,
  ...,
  .overwrite = FALSE,
  .destfile = NULL
) {
  template = ""
  if (!is.null(.template_name)) {
    if (fs::file_exists(.template_name)) {
      template = .template_name
    } else {
      template = system.file(
        sprintf("templates%stemplate-%s.R", .Platform$file.sep, .template_name),
        package = "pkgtools"
      )
    }
  }

  if (template == "") {
    template = template_choose()
  }

  lines = readr::read_lines(template)

  # this may or may not be a package project:
  wd = here::here()
  fs::dir_create(fs::path(wd, "R"))
  is_pkg = fs::file_exists(fs::path(wd, "DESCRIPTION"))

  dots = rlang::list2(...)
  # dots = list("test",b="test2")
  default = dots[[1]]
  named = dots[names(dots) != ""]
  subs = c(default, named)

  for (i in seq_along(subs)) {
    # i=1
    nm = names(subs)[[i]]
    nm = if (is.null(nm)) "" else nm
    value = subs[[i]]

    # Do ones where the template is quoted with double quotes
    regex = sprintf("\"([^\"`#]*)#%s#([^\"`]*)\"", nm)
    s = sprintf("\"\\1%s\\2\"", value)
    lines = gsub(regex, s, lines, perl = TRUE)

    # replace templates with normal characters (or none)
    regex = sprintf("`([\\.a-zA-Z0-9_]*)#%s#([\\.a-zA-Z0-9_]*)`", nm)
    s = sprintf("\\1%s\\2", value)
    lines = gsub(regex, s, lines, perl = TRUE)

    # Catch ones with special characters
    regex = sprintf("`([^`#]*)#%s#([^`]*)`", nm)
    s = sprintf("`\\1%s\\2`", value)
    lines = gsub(regex, s, lines, perl = TRUE)
  }

  yaml = .parse_yaml(lines)
  yaml$template_name = fs::path_file(template)
  dest_path = if (is.null(.destfile)) {
    fs::path(wd, "R", gsub("template-", "generated-", yaml$destfile))
  } else {
    .destfile
  }

  header = whisker::whisker.render(template_header, yaml)
  # Prepend a header
  lines = c(header, lines)

  if (fs::file_exists(dest_path) && !.overwrite) {
    if (interactive()) {
      # 3 way diff.
      merged = merge_code(
        old = readr::read_lines(dest_path),
        new = lines,
        value = readr::read_lines(dest_path),
        lhs = "original",
        rhs = "template"
      )
      readr::write_lines(merged, file = dest_path)
    } else {
      stop("Trying to write to: ", dest_path, " but it already exists.")
    }
  } else {
    readr::write_lines(lines, file = dest_path)
  }

  #TODO: deal with imports from the template.

  return(dest_path)
}


template_header = "# Templated file: may be overwritten
# Generated by: pkgtools from `{{template_name}}`
# ----------------------------------------------------------------------
"

#' modified copy of devtools:::standalone_choose
#'
#' @param names list of potential standalones from local or remote
#' @param error_call where to raise errors
#' @noRd
#'
#' @returns a single filename which will match standalone-*.R
template_choose = function() {
  files = fs::dir_ls(
    system.file("templates", package = "pkgtools"),
    glob = "*.R"
  )
  choices = gsub("^template-|.[Rr]$", "", fs::path_file(files))

  if (!rlang::is_interactive()) {
    cli::cli_abort(
      c(
        "`.template_name` is absent, but must be supplied.",
        i = "Possible options are {.or {choices}}."
      )
    )
  }
  choice <- utils::menu(
    choices = choices,
    title = "Which template do you want to use (0 to exit)?"
  )
  if (choice == 0) {
    cli::cli_abort("Selection cancelled")
  }
  files[[choice]]
}

# df = tempfile(fileext = ".R")

# devtools::load_all()
# file = use_template("struct","test", .destfile=df)
# source(file)

# tmp = as.test(1)
# tmp2 = as.test(2)
# rep(tmp,5)
# lst = c(rep(tmp,5),rep(tmp2,5))
# lst[4:8]
# c(lst,tmp,tmp2,lst)
# lst$value
# lst[[1]] = tmp2; lst
# lst[1:2] = rep(tmp2,2); lst
# lst[1:2] = tmp2; lst
# rep(lst,2)
# is.test_list(lst)
# is.test(lst[[1]])
# map_test(1:10, \(x) as.test(x))
# l = map2_test(1:10, 10:1, \(x,y) as.test(x, y=y))
# sort(l,decreasing=TRUE)

# rstudioapi::documentOpen(file)
